### ISSUE TITLE
Suggestion: Rebindable Controls

### ISSUE THREAD

**Issue by MinerB4** [matthewperiut/Entris#2]
When I first tried this mod I didn't really know the controls, and so I looked at controls to see what they were and couldn't find anything, I looked at the page to to see if it listed any controls... Nothin'
From what I noticed _while trying every key on the keyboard_ there were also two sets of controls as well.
If these were rebindable it would remove the need to have two sets as people can just change to what controls they're comfortable with.

**Comment by GoldenFurredFox** [comment]
From what I can tell:

Left arrow: Move left
Right arrow: Move right
Down arrow: Fast drop (move down the board faster)
Space bar: Hard drop (push to bottom and summon next part instantly)
Up arrow: Rotate clockwise
X: Rotate clockwise
Z: Rotate counterclockwise
C: Hold piece for later

**Comment by matthewperiut** [comment]
Done in the latest version for 1.21.x
