### ISSUE TITLE
Entris doesn't check for conflicting enchants

### ISSUE THREAD

**Issue by GoldenFurredFox** [matthewperiut/Entris#5]
## Versions:
Minecraft version: 1.20.1
Loader version: Fabric 0.16.5
Entris version: 0.1.2

## Steps to reproduce the issue:
1. Put an item to enchant and some lapis in the table, then complete a game of tetris
2. Select any conflicting enchants
3. All conflicting enchants remain

## What you expected to happen:
I expected to be unable to pick both Fortune and Silk Touch on my pickaxe

## What actually happened:
I could still have both Fortune and Silk Touch

## Did you test the bug with just your loader and the mods needed to reproduce the issue? And if so, did the issue still persist?
Yes, and yes.

- [X] I checked existing issues to ensure I'm not sending a duplicate issue.

**Comment by matthewperiut** [comment]
Fixed in 1.21.x
